#!/bin/bash

# ═══════════════════════════════════════════════════════════════════
# COMMANDES POUR REDÉMARRER LE BOT MANUELLEMENT
# ═══════════════════════════════════════════════════════════════════

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                                                                   ║"
echo "║   🚀 GUIDE DE REDÉMARRAGE DU BOT 🚀                              ║"
echo "║                                                                   ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 COMMANDES DISPONIBLES:"
echo ""
echo "1️⃣  REDÉMARRAGE SIMPLE (si port libre):"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  cd /Users/sheirraza/bsc-ranging-bot && npm start &        │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "2️⃣  REDÉMARRAGE FORCÉ (si port 3001 occupé):"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  lsof -ti:3001 | xargs kill -9; sleep 2                   │"
echo "    │  cd /Users/sheirraza/bsc-ranging-bot && npm start &        │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "3️⃣  REDÉMARRAGE EN UNE LIGNE (recommandé):"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  lsof -ti:3001 | xargs kill -9 2>/dev/null; sleep 2 &&    │"
echo "    │  cd /Users/sheirraza/bsc-ranging-bot && npm start &        │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 VÉRIFICATIONS APRÈS REDÉMARRAGE:"
echo ""
echo "📊 Vérifier que le bot tourne:"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  ps aux | grep AdvancedTradingBot | grep -v grep          │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "📜 Voir les logs en direct:"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  tail -f logs/combined.log                                │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "📈 Vérifier le monitoring des positions:"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  tail -20 logs/combined.log | grep \"Monitoring position\" │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "💾 Vérifier les trades:"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  sqlite3 data/trading_bot.db \"SELECT COUNT(*) FROM        │"
echo "    │  trades;\"                                                 │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🛑 ARRÊTER LE BOT:"
echo ""
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  pkill -f \"node.*AdvancedTradingBot\"                     │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "    Ou avec PID:"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  ps aux | grep AdvancedTradingBot | grep -v grep          │"
echo "    │  kill -9 <PID>                                             │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 MONITORING AUTOMATIQUE:"
echo ""
echo "    Le monitoring continue indépendamment du bot principal."
echo "    Rapports générés toutes les heures dans:"
echo "    • logs/position-monitoring.log"
echo ""
echo "    Commandes monitoring:"
echo "    ┌────────────────────────────────────────────────────────────┐"
echo "    │  ./start-monitoring.sh    (démarrer)                      │"
echo "    │  ./stop-monitoring.sh     (arrêter)                       │"
echo "    │  tail -f logs/position-monitoring.log  (suivre)           │"
echo "    └────────────────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ BOT REDÉMARRÉ AVEC SUCCÈS!"
echo ""
echo "    Le bot est maintenant actif et surveille vos 133 positions."
echo "    Premières sorties attendues dans 3-4 heures (TP 0.8%)."
echo ""
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""






